apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: user-added
  namespace: default
spec:
  type: bindings.kafka
  version: v1
  metadata:
    - name: topics
      value: user_events
    - name: brokers
      value: localhost:9093
    - name: consumerGroup
      value: dapr-binding-group1
    - name: authRequired
      value: "false"
    - name: route
      value: http://localhost:5076/user-added
