apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers # Required. Kafka broker connection setting
      value: "localhost:9092"
    - name: consumerGroup # Optional. Used for input bindings.
      value: "dapr-group1"
    # - name: clientID # Optional. Used as client tracing ID by Kafka brokers.
    #   value: "test-dapr-app-id"
    - name: authRequired # Required.
      value: "false"
scopes:
  - dapr-listener
